<h1>About Dataset</h1>

<h3>Context</h3>
<p>Predict behaviour to retain customers.</p>

<h3>Content</h3>
<p>Each row represents a customer, each column contains customer's attributes described in the column metadata.
The dataset includes information about:
  <ul>
    <li>Churn: Customers who left within the last month.</li>
    <li>Customer account information</li>
    <li>Services that a customer has signed up for, such as Phone, Internet, Streaming TV and movies, etc. (Telco -> Some Telecommunications company)</li>
    <li>Demographic information such as Gender, Age, etc.</li>
</ul>
</p>

<h1>Exploration & Data Loading</h1>

In [199]:
import pandas as pd # For working with data in a tabular form
import seaborn as sns # For visualizing the data
import matplotlib.pyplot as plt # For visualizing the data
import numpy as np

In [200]:
df = pd.read_csv("../data/raw/Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [201]:
df.describe(include="all")

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,7043,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,6531,2
top,7590-VHVEG,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,20.2,No
freq,1,3555,NaN,3641,4933,NaN,6361,3390,3096,3498,...,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

<h1> Binary Encoding </h1>
<p> For categorical variables with 2 categories.</p>

In [202]:
binary_cols = [col for col in df.columns if len(df[col].unique()) == 2]
for col in binary_cols:
  first_category, second_category = df[col].unique()[0], df[col].unique()[1]
  print(f"Categories of {col}: ", first_category, ",", second_category)

Categories of gender:  Female , Male
Categories of SeniorCitizen:  0 , 1
Categories of Partner:  Yes , No
Categories of Dependents:  No , Yes
Categories of PhoneService:  No , Yes
Categories of PaperlessBilling:  Yes , No
Categories of Churn:  No , Yes

In [203]:
pd.set_option('future.no_silent_downcasting', True)

In [204]:
df[binary_cols] = df[binary_cols].replace({
  "Yes": 1, "No": 0, "Male": 1, "Female": 0
})

In [205]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,No phone service,DSL,No,...,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,No,DSL,Yes,...,Yes,No,No,No,One year,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,1,0,0,0,2,1,No,DSL,Yes,...,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,45,0,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,No,Fiber optic,No,...,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1

<h1> Exploring the data in the 'TotalCharges' column </h1>
<p> The data in the TotalCharges column is of the datatype 'object', so we explore the column further to see if it contains a mix of different primitive datatypes. If yes, we can clean it up a bit and convert the column to the proper numeric format.</p>

In [206]:
# df['TotalCharges'] should contain numerical values, however its datatype is object, which suggest that the column may be a mix of different primitive datatypes
df['TotalCharges'].dtype.name

'object'

In [207]:
# Exploring the data in the 'TotalCharges' column
df['TotalCharges'].isnull().value_counts() # No null values in this column

TotalCharges
False    7043
Name: count, dtype: int64

In [208]:
# Profiling the column's primitive data types in the 'TotalCharges' column
df['TotalCharges'].apply(type).value_counts() # All 'objects' in the column have a the primitive 'string' datatype

TotalCharges
<class 'str'>    7043
Name: count, dtype: int64

In [209]:
# Checking if there are any empty strings in the column 'TotalCharges'
empty_string_indexes = df.loc[(df['TotalCharges'].isin(['', ' '])), 'TotalCharges'].index.to_numpy() # Empty strings are present in some rows of the 'TotalCharges' Column
empty_string_indexes

array([ 488,  753,  936, 1082, 1340, 3331, 3826, 4380, 5218, 6670, 6754])

In [210]:
# Checking if there are any strings with non-numeric content in the column 'TotalCharges'
non_numeric_string_indexes = df.loc[df['TotalCharges'].str.contains(r'[^\d.\s]', na=False), 'TotalCharges'].index.to_numpy() # No non-numeric string values aside from the empty strings ('' and ' ')
non_numeric_string_indexes

array([], dtype=int64)

In [211]:
# Coverting the 'TotalCharges' column of 'Object' datatype back to a number, all rows having an empty string are replaced with NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [212]:
# There are 11 rows with NaN as their Total Charges
df['TotalCharges'].isna().value_counts()

TotalCharges
False    7032
True       11
Name: count, dtype: int64

<h1> One-Hot Encoding </h1>
<p> For categorical variables with more than 2 categories </p>

In [213]:
one_hot_cols = [col for col in df.columns if len(df[col].unique()) > 2 and type(df[col].dropna().sample(n=1).values[0]) is str]
one_hot_cols.remove('customerID')
one_hot_cols

['MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaymentMethod']

In [214]:
df = pd.get_dummies(df, columns=one_hot_cols, drop_first=True)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,0,1,0,1,0,1,29.85,29.85,...,False,False,False,False,False,False,False,False,True,False
1,5575-GNVDE,1,0,0,0,34,1,0,56.95,1889.50,...,False,False,False,False,False,True,False,False,False,True
2,3668-QPYBK,1,0,0,0,2,1,1,53.85,108.15,...,False,False,False,False,False,False,False,False,False,True
3,7795-CFOCW,1,0,0,0,45,0,0,42.30,1840.75,...,True,False,False,False,False,True,False,False,False,False
4,9237-HQITU,0,0,0,0,2,1,1,70.70,151.65,...,False,False,False,False,False,False,False,False,True,False

<h1> Data Cleaning </h1>
<p> After transforming one column ('TotalCharges') of the Dataframe df, there is still some more Data exploration and cleaning to do. </p>

In [215]:
# Customer ID is irrelevant for Churn prediction
df = df.drop('customerID', axis=1)

In [216]:
# Converting all the True/False (boolean values) to 0/1 (numeric values)
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,0,...,0,0,0,0,0,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,0,0,0,0,0,1,0,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,1,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,1,0,0,0,0,1,0,0,0,0
4,0,0,0,0,2,1,1,70.70,151.65,1,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,84.80,1990.50,0,...,1,0,1,0,1,1,0,0,0,1
7039,0,0,1,1,72,1,1,103.20,7362.90,0,...,0,0,1,0,1,1,0,1,0,0
7040,0,0,1,1,11,0,1,29.60,346.45,0,...,0,0,0,0,0,0,0,0,1,0
7041,1,1,1,0,4,1,1,74.40,306.60,1,...,0,0,0,0,0,0,0,0,0,1
7042,1,0,0,0,66,1,1,105.65,6844.50,0,...,1,0,1,0,1,0,1,0,0,0

In [217]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7043 non-null   object
 1   SeniorCitizen                          7043 non-null   int64
 2   Partner                                7043 non-null   object
 3   Dependents                             7043 non-null   object
 4   tenure                                 7043 non-null   int64
 5   PhoneService                           7043 non-null   object
 6   PaperlessBilling                       7043 non-null   object
 7   MonthlyCharges                         7043 non-null   float64
 8   TotalCharges                           7032 non-null   float64
 9   Churn                                  7043 non-null   object
 10  MultipleLines_No phone service         7043 non-null   int64
 11  MultipleLines_Yes                      7043 non-null   int64
 12  InternetService_Fiber optic            7043 non-null   int64
 13  InternetService_No                     7043 non-null   int64
 14  OnlineSecurity_No internet service     7043 non-null   int64
 15  OnlineSecurity_Yes                     7043 non-null   int64
 16  OnlineBackup_No internet service       7043 non-null   int64
 17  OnlineBackup_Yes                       7043 non-null   int64
 18  DeviceProtection_No internet service   7043 non-null   int64
 19  DeviceProtection_Yes                   7043 non-null   int64
 20  TechSupport_No internet service        7043 non-null   int64
 21  TechSupport_Yes                        7043 non-null   int64
 22  StreamingTV_No internet service        7043 non-null   int64
 23  StreamingTV_Yes                        7043 non-null   int64
 24  StreamingMovies_No internet service    7043 non-null   int64
 25  StreamingMovies_Yes                    7043 non-null   int64
 26  Contract_One year                      7043 non-null   int64
 27  Contract_Two year                      7043 non-null   int64
 28  PaymentMethod_Credit card (automatic)  7043 non-null   int64
 29  PaymentMethod_Electronic check         7043 non-null   int64
 30  PaymentMethod_Mailed check             7043 non-null   int64
dtypes: float64(2), int64(23), object(6)
memory usage: 1.7+ MB

In [218]:
# The Churn column has datatype 'Object', which we will convert to a numeric datatype
df['Churn'].dtype.name

'object'

In [ ]:
# Converting Churn (having "Object" datatype to an int datatype)
df["Churn"] = df['Churn'].astype(np.int64)